micronaut:
  application:
    name: hbuddyApp
  api:
    swagger:
      path: /api-docs/swagger
      version: 3.19.4
      layout: StandaloneLayout
      deepLinking: true
#      urls:
#        - name: hbuddy
#          url: /api-docs/swagger/hbuddy-1.0.yml
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: ${application.api.swagger.path}/**
  session:
    http:
      cookie: true
      header: true
      redis:
        enabled: true
ribbon:
  VipAddress: test
  ServerListRefreshInterval: 2000
  
mongodb:
  uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/hbuddy
  options:
    maxConnectionIdleTime: 10000
    readConcern: majority
    
kafka.bootstrap.servers: localhost:9092

redis:
    uri: redis://localhost
    io-thread-pool-size: 5
    computation-thread-pool-size: 4
    
hbuddy:
  db: hbuddy