micronaut:
  application:
    name: hbuddyApp
  session:
    http:
      cookie: true
      header: true
      redis:
        enabled: true
ribbon:
  VipAddress: test
  ServerListRefreshInterval: 2000
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}
redis.uri: redis://localhost
kafka.bootstrap.servers: localhost:9092
